<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;

class Order extends Model
{
    use HasUuids;

    protected $keyType = 'string';
    public $incrementing = false;

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'user_id',
        'partner_id',
        'employee_id',
        'coupon_id',
        'no_orders',
        'status',
        'channel',
        'pickup_address',
        'delivery_address',
        'same_location',
        'poin_digunakan',
        'poin_didapat',
        'total_harga',
        'diskon',
        'harga_akhir',
    ];

    /**
     * The attributes that should be cast.
     */
    protected $casts = [
        'same_location'  => 'boolean',
        'poin_digunakan' => 'integer',
        'poin_didapat'   => 'integer',
        'total_harga'    => 'decimal:2',
        'diskon'         => 'decimal:2',
        'harga_akhir'    => 'decimal:2',
    ];

    // -------------------------------------------------------------------------
    // Relationships
    // -------------------------------------------------------------------------

    /** Customer who placed the order */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    /** Partner that handled this order */
    public function partner(): BelongsTo
    {
        return $this->belongsTo(Partner::class);
    }

    /** Employee assigned to this order */
    public function employee(): BelongsTo
    {
        return $this->belongsTo(User::class, 'employee_id');
    }

    /** Coupon applied to this order */
    public function coupon(): BelongsTo
    {
        return $this->belongsTo(Coupon::class);
    }

    /** Line items within this order */
    public function items(): HasMany
    {
        return $this->hasMany(OrderItem::class);
    }

    /** Status change history for this order */
    public function statusLogs(): HasMany
    {
        return $this->hasMany(StatusLog::class);
    }

    /** Commission generated by this order */
    public function commission(): HasOne
    {
        return $this->hasOne(Commission::class);
    }

    /** Point logs created from this order */
    public function poinLogs(): HasMany
    {
        return $this->hasMany(PoinLog::class);
    }

    /** Affiliate referral that led to this order */
    public function affiliateReferral(): HasOne
    {
        return $this->hasOne(AffiliateReferral::class);
    }

    // -------------------------------------------------------------------------
    // Scopes
    // -------------------------------------------------------------------------

    public function scopeStatus($query, string $status)
    {
        return $query->where('status', $status);
    }

    public function scopeChannel($query, string $channel)
    {
        return $query->where('channel', $channel);
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    /** Check if order can still be cancelled */
    public function isCancellable(): bool
    {
        return in_array($this->status, ['waiting', 'pickUp']);
    }
}
